/**
 * ATLAS Connect — Business Collaboration Platform module.
 */

export type {
  ConnectWorkspace,
  ConnectChannel,
  ConnectConversation,
  ConnectMessage,
  ConnectParticipant,
  ConnectTask,
  ConnectMeeting,
  ConnectCall,
  ConnectApproval,
  ConnectCalendarEvent,
  ConnectSharedFile,
  ConnectAnnouncement,
  ConnectMessageReaction,
  ConnectAttachment,
  ConnectThread,
  ConnectMessageType,
  ConnectConversationKind,
  ConnectChannelType,
  ConnectActionType,
  ConnectReferenceType,
  ConnectMonetizationFeature,
  SendMessageInput,
  CreateConversationInput,
} from "./types";

export { CONNECT_EVENT_HANDLERS, DEFAULT_CONNECT_CHANNELS } from "./types";

export {
  ensureBusinessConnect,
  getBusinessWorkspace,
  listWorkspaceConversations,
  getConversationMessages,
  getWorkspaceChannels,
  getConversationParticipants,
  createChannel,
  sendMessage,
  createConversation,
  convertMessageToTask,
  convertMessageAction,
  scheduleMeeting,
  startMeeting,
  endMeeting,
  startCall,
  reactToMessage,
  attachToMessage,
  openThread,
  pinMessage,
  publishAnnouncement,
  requestApproval,
  scheduleCalendarEvent,
  shareBusinessFile,
  shareMarketplaceEntity,
  searchWorkspace,
  handleConnectDomainEvent,
  createAtlasConnectPort,
  suggestMessageActions,
  primaryActionForMessageType,
  workspaceChannel,
  conversationChannel,
  userInboxChannel,
  meetingChannel,
  presenceChannel,
  buildRealtimePayload,
  subscriptionsForWorkspace,
  CONNECT_AI_CAPABILITIES,
  createConnectAiStubResult,
  recommendNextActionsFromMessage,
  CONNECT_SEARCH_SCOPES,
  rankSearchHits,
  scoreTextMatch,
  tokenizeSearchQuery,
  DEFAULT_CONNECT_NOTIFICATION_PREFS,
  resolveDeliveryChannels,
  buildNotificationEnvelope,
  assessMessageSpam,
  encryptionReadyDefaults,
  buildPermissionAuditEntry,
  isAttachmentSafeToShare,
} from "./service";

export { registerAtlasConnectEventHandlers } from "./events";

export {
  assertUuid,
  assertMessageType,
  assertConversationKind,
  validateSendMessageInput,
  sendMessageSchema,
  createConversationSchema,
  createChannelSchema,
  scheduleMeetingSchema,
  searchConnectSchema,
} from "./validators";
