/**
 * ATLAS Platform — Bounded Context Map
 * ------------------------------------
 * ATLAS is the Business Operating System. Bounded contexts are capabilities
 * inside ATLAS — not separate products.
 *
 * Business (internal: businessHub) owns the company aggregate.
 * Marketplace is a sales channel — never the platform identity.
 *
 * Rule: modules communicate through contracts in `domains/contracts`.
 * No module may import another module's internals.
 */

export const BOUNDED_CONTEXTS = {
  authentication: {
    id: "authentication",
    owns: ["User", "Session", "Credential", "OAuthAccount", "WalletLink"],
    existingCode: ["modules/auth", "auth.ts", "lib/auth"],
  },
  businessHub: {
    id: "business_hub",
    /** Public ATLAS module: Business */
    atlasModule: "business",
    owns: [
      "Business",
      "BusinessProfile",
      "BusinessVerification",
      "BusinessMembership",
      "BusinessSettings",
      "Store",
      "Product",
      "Employee",
      "BusinessWallet",
      "BusinessAnalytics",
      "BusinessAiContext",
    ],
    existingCode: [
      "modules/business-hub",
      "modules/stores",
      "modules/verification",
      "modules/catalog",
      "modules/platform",
    ],
    note: "ATLAS Business capability (legacy: Business Hub). Owns Store/Product masters, membership, settings, and business-scoped wallet/analytics/AI context. Marketplace consumes — never owns — these.",
  },
  marketplace: {
    id: "marketplace",
    atlasModule: "marketplace",
    owns: [
      "Listing",
      "MarketplaceListing",
      "MarketplaceStorefront",
      "MarketplaceOffer",
      "MarketplaceFlashSale",
      "MarketplaceCampaign",
      "MarketplaceCollection",
      "MarketplaceCheckout",
      "MarketplaceShipment",
      "MarketplaceFavorite",
      "MarketplaceRecommendation",
      "MarketplaceAdvertisement",
      "MarketplaceTag",
      "MarketplaceMonetizationLedger",
      "Cart",
      "Wishlist",
      "Storefront",
      "Review",
      "Discovery",
    ],
    existingCode: ["modules/atlas-marketplace", "modules/marketplace"],
    note: "ATLAS sales channel / Commerce Engine. Consumes Business Store & Product masters only. Listing is a channel projection — never a second Product master.",
  },
  catalog: {
    id: "catalog",
    owns: ["Category", "Brand", "InventoryItem"],
    existingCode: ["modules/catalog", "modules/marketplace/catalog"],
    note: "Operational catalog workflows; Product master ownership sits with ATLAS Business (business_id).",
  },
  orders: {
    id: "orders",
    owns: ["Order", "OrderLine", "Fulfillment"],
    existingCode: ["modules/orders"],
  },
  payments: {
    id: "payments",
    owns: ["Payment", "PaymentSession", "Invoice", "Escrow", "Settlement"],
    existingCode: [
      "modules/payments",
      "modules/invoices",
      "modules/escrow",
      "modules/settlement",
      "modules/settlement-reports",
    ],
  },
  wallet: {
    id: "wallet",
    owns: ["Wallet", "LedgerEntry", "Withdrawal"],
    existingCode: ["modules/wallet", "modules/withdrawals", "modules/chains"],
  },
  nxrToken: {
    id: "nxr_token",
    /** Public ATLAS module: NXR */
    atlasModule: "nxr",
    owns: [
      "TokenAccount",
      "TokenTransfer",
      "PresalePosition",
      "NxrToken",
      "NxrWallet",
      "NxrBalance",
      "NxrTransaction",
      "NxrReward",
      "NxrRewardRule",
      "NxrRewardCampaign",
      "NxrLoyaltyAccount",
      "NxrBusinessCredits",
      "NxrTokenPayment",
      "NxrTokenLedger",
      "NxrExchangeRate",
      "NxrTreasury",
      "NxrReserve",
      "NxrBurnEvent",
      "NxrMintEvent",
      "NxrPremiumActivation",
      "NxrStakingPool",
      "NxrGovernanceProposal",
    ],
    existingCode: ["modules/atlas-nxr", "lib/web3", "lib/blockchain", "app/presale"],
    note: "NXR Token Ecosystem — native utility token of ATLAS. Off-chain ledger first; blockchain adapters optional. Does not own fiat Wallet masters.",
  },
  partners: {
    id: "partners",
    owns: ["Partnership", "PartnerInvite", "Referral"],
    existingCode: [],
    status: "planned",
  },
  atlasNetwork: {
    id: "atlas_network",
    /** Public ATLAS module: Network */
    atlasModule: "network",
    owns: [
      "Profile",
      "CompanyProfile",
      "Organization",
      "Connection",
      "Follow",
      "Post",
      "Article",
      "Announcement",
      "Media",
      "Comment",
      "Reaction",
      "Share",
      "Bookmark",
      "Tag",
      "Hashtag",
      "Mention",
      "Group",
      "Community",
      "Page",
      "Event",
      "Poll",
      "Conversation",
      "Message",
      "Attachment",
      "Activity",
      "Timeline",
    ],
    existingCode: ["modules/atlas-network"],
    note: "ATLAS Network — Business Social Network. Not social media. Business-first professional graph, feed, chat, and discovery.",
  },
  /** @deprecated Use atlasNetwork — kept for backward-compatible imports */
  businessNetwork: {
    id: "atlas_network",
    atlasModule: "network",
    owns: ["Connection", "Introduction", "NetworkProfile"],
    existingCode: ["modules/atlas-network"],
    status: "deprecated",
    note: "Alias of atlasNetwork. Do not use in new code.",
  },
  atlasPulse: {
    id: "atlas_pulse",
    /** Public ATLAS module: Pulse (Feed) */
    atlasModule: "feed",
    owns: [
      "PulseFeed",
      "PulseFeedItem",
      "PulseTimeline",
      "PulseActivity",
      "BusinessUpdate",
      "PulseAnnouncement",
      "PulseArticle",
      "BusinessInsight",
      "TrendingTopic",
      "TrendingBusiness",
      "TrendingProduct",
      "TrendingService",
      "PulseHashtag",
      "PulseMention",
      "PulseBookmark",
      "PulseReaction",
      "PulseComment",
      "PulseShare",
      "PulseCollection",
      "PulseRecommendation",
      "FeedPreference",
      "FeedCategory",
    ],
    existingCode: ["modules/atlas-pulse"],
    note: "ATLAS Pulse — Business Intelligence Feed. Real-time activity engine; ingests all ecosystem events. Not social media.",
  },
  atlasConnect: {
    id: "atlas_connect",
    /** Public ATLAS module: Connect */
    atlasModule: "connect",
    owns: [
      "ConnectWorkspace",
      "ConnectWorkspaceMember",
      "ConnectDepartment",
      "ConnectTeam",
      "ConnectConversation",
      "ConnectChannel",
      "ConnectParticipant",
      "ConnectMessage",
      "ConnectMessageReaction",
      "ConnectAttachment",
      "ConnectThread",
      "ConnectAnnouncement",
      "ConnectPinnedMessage",
      "ConnectTask",
      "ConnectApproval",
      "ConnectEntityReference",
      "ConnectMeeting",
      "ConnectCall",
      "ConnectCalendarEvent",
      "ConnectSharedFile",
      "ConnectMessageAction",
      "ConnectAuditLog",
      "ConnectNotificationPrefs",
      "ConnectDeviceSession",
    ],
    existingCode: ["modules/atlas-connect"],
    note: "ATLAS Connect — Business Collaboration Platform. Not a chat app. Communication becomes business actions. Prefixed Connect* aggregates — Network retains social Conversation/Message tables as legacy DMs.",
  },
  atlasAi: {
    id: "atlas_ai",
    /** Public ATLAS module: AI */
    atlasModule: "ai",
    owns: [
      "AiWorkspace",
      "AiBusinessContext",
      "AiAgent",
      "AiConversation",
      "AiMessage",
      "AiMemory",
      "AiKnowledgeItem",
      "AiVectorDocument",
      "AiEmbedding",
      "AiModel",
      "AiPrompt",
      "AiPromptTemplate",
      "AiTool",
      "AiWorkflow",
      "AiAutomation",
      "AiTask",
      "AiPlannedAction",
      "AiExecution",
      "AiInsight",
      "AiRecommendation",
      "AiPrediction",
      "AiReport",
      "AiCreditLedger",
    ],
    existingCode: ["modules/atlas-ai"],
    note: "ATLAS AI — Business Intelligence Engine. Not a chatbot. Provider-agnostic LLM-ready operating intelligence. Legacy modules/ai assistant stubs remain under context `ai` until absorbed.",
  },
  atlasApps: {
    id: "atlas_apps",
    /** Public ATLAS module: Apps */
    atlasModule: "apps",
    owns: [
      "AppApplication",
      "AppInstall",
      "AppBusinessApplication",
      "AppCategory",
      "AppPermission",
      "AppSubscription",
      "AppVersion",
      "AppUpdate",
      "AppDeveloper",
      "AppReview",
      "AppRating",
      "AppLicense",
      "AppWebhook",
      "AppSettings",
      "AppApiKey",
      "AppAuditLog",
      "AppEarnings",
    ],
    existingCode: ["modules/atlas-apps"],
    note: "ATLAS Apps — Business Applications Platform. Expandable BOS plugin layer (App Store). Does not own Business/Product/Order masters. Prefixed App* — jobs context retains Application (job applications).",
  },
  atlasFinance: {
    id: "atlas_finance",
    /** Public ATLAS module: Finance */
    atlasModule: "finance",
    owns: [
      "FinanceWorkspace",
      "FinanceChartOfAccounts",
      "FinanceAccount",
      "FinanceJournal",
      "FinanceJournalEntry",
      "FinanceLedger",
      "FinanceTransaction",
      "FinanceQuotation",
      "FinancePurchaseOrder",
      "FinanceExpense",
      "FinanceIncome",
      "FinanceTax",
      "FinanceTaxRate",
      "FinanceCostCenter",
      "FinanceBudget",
      "FinancePeriod",
      "FinanceCreditNote",
      "FinanceDebitNote",
      "FinanceRefund",
      "FinanceRecurringInvoice",
      "FinanceRecurringExpense",
      "FinanceSubscription",
      "FinanceInstallment",
      "FinanceReportSnapshot",
      "FinanceAuditLog",
    ],
    existingCode: ["modules/atlas-finance"],
    note: "ATLAS Finance — Financial Operating System. Double-entry GL, tax, budgets, reports. Consumes Invoice/Payment/Wallet masters from payments/wallet — never duplicates them. Legacy modules/payments & modules/invoices remain payment rails.",
  },
  atlasMobile: {
    id: "atlas_mobile",
    /** Public ATLAS module: Mobile */
    atlasModule: "mobile",
    owns: [
      "MobileDevice",
      "MobileSession",
      "MobilePushToken",
      "MobilePushDelivery",
      "MobileOfflineQueueItem",
      "MobileSyncCursor",
      "MobileSyncConflict",
      "MobileDeepLink",
      "MobileCameraJob",
      "MobileLocationPing",
      "MobileDashboardWidget",
      "MobileEntitlement",
      "MobileRemoteCommand",
      "MobileAnalyticsEvent",
      "MobileAuditLog",
    ],
    existingCode: ["modules/atlas-mobile"],
    note: "ATLAS Mobile — complete mobile platform layer. Offline-first sync, push, devices, deep links, camera contracts. Never owns Business/Product/Order masters — same data as desktop via ports.",
  },
  atlasCore: {
    id: "atlas_core",
    /** Public ATLAS module: Core */
    atlasModule: "core",
    owns: [
      "CoreOutboxMessage",
      "CoreTimelineEvent",
      "CoreSearchDocument",
      "CoreAnalyticsFact",
      "CoreWorkflowRun",
      "CoreNotificationDispatch",
    ],
    existingCode: ["modules/atlas-core"],
    note: "ATLAS Core — One Platform / One Brain. Orchestration workflows, durable outbox, unified timeline/search/analytics bridge, notification hub. Does not own Business/Product/Order masters.",
  },
  employees: {
    id: "employees",
    owns: ["Team", "RoleAssignment", "EmployeeWorkflow"],
    existingCode: [],
    status: "planned",
    note: "Operational HR workflows; Employee master aggregate is owned by ATLAS Business.",
  },
  documents: {
    id: "documents",
    owns: ["Document", "DocumentVersion", "SignatureRequest"],
    existingCode: [],
    status: "planned",
  },
  ai: {
    id: "ai",
    owns: ["AssistantThread", "AssistantMessage", "AiAction"],
    existingCode: ["modules/ai"],
    status: "foundation",
    note: "Legacy global/merchant assistant stubs. ATLAS AI pillar is `atlasAi` (`modules/atlas-ai`). Do not add new intelligence features here.",
  },
  analytics: {
    id: "analytics",
    owns: ["MetricSnapshot"],
    derivesFrom: "domain_events",
    existingCode: [
      "modules/analytics",
      "modules/marketplace/analytics",
      "modules/atlas-core",
    ],
    note: "Legacy SQL aggregates + ATLAS Core event facts (`atlas_core_analytics_facts`).",
  },
  notifications: {
    id: "notifications",
    owns: ["Notification", "NotificationPreference"],
    existingCode: ["modules/notifications"],
  },
  search: {
    id: "search",
    owns: ["SearchIndex"],
    existingCode: ["modules/search", "modules/marketplace/discovery", "modules/atlas-core"],
    note: "Legacy global_search RPC + ATLAS Core search documents (`atlas_core_search_documents`).",
  },
  settings: {
    id: "settings",
    owns: ["UserSettings", "PlatformSettings"],
    existingCode: ["modules/platform"],
    note: "BusinessSettings live under ATLAS Business (businesses.settings JSONB).",
  },
  administration: {
    id: "administration",
    owns: ["AdminAction", "ModerationCase", "PlatformBan"],
    existingCode: ["modules/platform", "lib/admin", "app/admin"],
    status: "foundation",
    note:
      "Legacy context id — evolved into NEXAR HQ (`atlasHq`). Keep for ownership aliases; do not build a second admin panel.",
  },
  atlasHq: {
    id: "atlas_hq",
    atlasModule: "nexar-hq",
    owns: [
      "HqBootstrap",
      "HqPlatformOwner",
      "HqTeamMember",
      "HqCustomRole",
      "HqWebsitePage",
      "HqWebsiteSection",
      "HqWebsiteGlobals",
      "HqAnnouncement",
      "HqMediaAsset",
      "HqEmailTemplate",
      "AdminAction",
      "ModerationCase",
      "PlatformBan",
    ],
    existingCode: [
      "modules/atlas-hq",
      "modules/platform",
      "modules/ticker",
      "lib/admin",
      "lib/hq",
      "app/admin",
    ],
    status: "foundation",
    note:
      "NEXAR HQ — sole internal administration of ATLAS. Legacy /admin reuses HQ services & permissions.",
  },
  media: {
    id: "media",
    owns: ["MediaAsset"],
    existingCode: ["lib/supabase (storage)"],
  },
  reviews: {
    id: "reviews",
    owns: ["Review", "RatingAggregate"],
    existingCode: ["modules/marketplace/reviews"],
  },
  events: {
    id: "events",
    owns: ["DomainEvent"],
    existingCode: ["domains/events"],
    status: "foundation",
    note: "In-process bus + catalog. Durable OutboxMessage implemented by atlasCore (`atlas_core_outbox`).",
  },
  jobs: {
    id: "jobs",
    owns: ["JobPosting", "Application"],
    existingCode: [],
    status: "planned",
  },
  api: {
    id: "api",
    owns: ["ApiKey", "WebhookEndpoint", "WebhookDelivery"],
    existingCode: ["modules/public-api", "modules/webhooks"],
  },
  audit: {
    id: "audit",
    owns: ["AuditLog", "SecurityLog"],
    existingCode: ["modules/audit"],
  },
} as const;

export type BoundedContextId = keyof typeof BOUNDED_CONTEXTS;

/** Contexts that already have production code in this repo. */
export const ACTIVE_CONTEXTS: BoundedContextId[] = [
  "authentication",
  "businessHub",
  "atlasNetwork",
  "atlasPulse",
  "atlasConnect",
  "atlasAi",
  "atlasApps",
  "atlasFinance",
  "atlasMobile",
  "atlasCore",
  "marketplace",
  "catalog",
  "orders",
  "payments",
  "wallet",
  "nxrToken",
  "ai",
  "analytics",
  "notifications",
  "search",
  "settings",
  "administration",
  "atlasHq",
  "media",
  "reviews",
  "api",
  "audit",
];
