/**
 * Aggregate ownership — single source of truth matrix.
 * ATLAS Business owns company master data.
 * ATLAS Network owns social graph entities.
 * ATLAS Pulse owns intelligence feed & trending.
 * Marketplace owns only sales-channel aggregates.
 */

import type { BoundedContextId } from "./map";

export const AGGREGATE_OWNER: Record<string, BoundedContextId> = {
  User: "authentication",
  Session: "authentication",

  Business: "businessHub",
  BusinessProfile: "businessHub",
  BusinessVerification: "businessHub",
  BusinessMembership: "businessHub",
  BusinessSettings: "businessHub",
  Store: "businessHub",
  Product: "businessHub",
  Employee: "businessHub",
  BusinessWallet: "businessHub",
  BusinessAnalytics: "businessHub",
  BusinessAiContext: "businessHub",

  // ATLAS Network — Business Social Network
  Profile: "atlasNetwork",
  CompanyProfile: "atlasNetwork",
  Organization: "atlasNetwork",
  Connection: "atlasNetwork",
  Follow: "atlasNetwork",
  Post: "atlasNetwork",
  Article: "atlasNetwork",
  Announcement: "atlasNetwork",
  NetworkMedia: "atlasNetwork",
  Comment: "atlasNetwork",
  Reaction: "atlasNetwork",
  Share: "atlasNetwork",
  Bookmark: "atlasNetwork",
  Tag: "atlasNetwork",
  Hashtag: "atlasNetwork",
  Mention: "atlasNetwork",
  Group: "atlasNetwork",
  Community: "atlasNetwork",
  Page: "atlasNetwork",
  NetworkEvent: "atlasNetwork",
  Poll: "atlasNetwork",
  Conversation: "atlasNetwork",
  Message: "atlasNetwork",
  Attachment: "atlasNetwork",
  Activity: "atlasNetwork",
  Timeline: "atlasNetwork",
  /** @deprecated alias */
  NetworkProfile: "atlasNetwork",
  Introduction: "atlasNetwork",

  // ATLAS Pulse — Business Intelligence Feed
  PulseFeed: "atlasPulse",
  PulseFeedItem: "atlasPulse",
  PulseTimeline: "atlasPulse",
  PulseActivity: "atlasPulse",
  BusinessUpdate: "atlasPulse",
  PulseAnnouncement: "atlasPulse",
  PulseArticle: "atlasPulse",
  BusinessInsight: "atlasPulse",
  TrendingTopic: "atlasPulse",
  TrendingBusiness: "atlasPulse",
  TrendingProduct: "atlasPulse",
  TrendingService: "atlasPulse",
  PulseHashtag: "atlasPulse",
  PulseMention: "atlasPulse",
  PulseBookmark: "atlasPulse",
  PulseReaction: "atlasPulse",
  PulseComment: "atlasPulse",
  PulseShare: "atlasPulse",
  PulseCollection: "atlasPulse",
  PulseRecommendation: "atlasPulse",
  FeedPreference: "atlasPulse",
  FeedCategory: "atlasPulse",

  // ATLAS Connect — Business Collaboration Platform
  ConnectWorkspace: "atlasConnect",
  ConnectWorkspaceMember: "atlasConnect",
  ConnectDepartment: "atlasConnect",
  ConnectTeam: "atlasConnect",
  ConnectConversation: "atlasConnect",
  ConnectChannel: "atlasConnect",
  ConnectParticipant: "atlasConnect",
  ConnectMessage: "atlasConnect",
  ConnectMessageReaction: "atlasConnect",
  ConnectAttachment: "atlasConnect",
  ConnectThread: "atlasConnect",
  ConnectAnnouncement: "atlasConnect",
  ConnectPinnedMessage: "atlasConnect",
  ConnectTask: "atlasConnect",
  ConnectApproval: "atlasConnect",
  ConnectEntityReference: "atlasConnect",
  ConnectMeeting: "atlasConnect",
  ConnectCall: "atlasConnect",
  ConnectCalendarEvent: "atlasConnect",
  ConnectSharedFile: "atlasConnect",
  ConnectMessageAction: "atlasConnect",
  ConnectAuditLog: "atlasConnect",
  ConnectNotificationPrefs: "atlasConnect",
  ConnectDeviceSession: "atlasConnect",

  // ATLAS AI — Business Intelligence Engine
  AiWorkspace: "atlasAi",
  AiBusinessContext: "atlasAi",
  AiAgent: "atlasAi",
  AiConversation: "atlasAi",
  AiMessage: "atlasAi",
  AiMemory: "atlasAi",
  AiKnowledgeItem: "atlasAi",
  AiVectorDocument: "atlasAi",
  AiEmbedding: "atlasAi",
  AiModel: "atlasAi",
  AiPrompt: "atlasAi",
  AiPromptTemplate: "atlasAi",
  AiTool: "atlasAi",
  AiWorkflow: "atlasAi",
  AiAutomation: "atlasAi",
  AiTask: "atlasAi",
  AiPlannedAction: "atlasAi",
  AiExecution: "atlasAi",
  AiInsight: "atlasAi",
  AiRecommendation: "atlasAi",
  AiPrediction: "atlasAi",
  AiReport: "atlasAi",
  AiCreditLedger: "atlasAi",

  // ATLAS Apps — Business Applications Platform
  AppApplication: "atlasApps",
  AppInstall: "atlasApps",
  AppBusinessApplication: "atlasApps",
  AppCategory: "atlasApps",
  AppPermission: "atlasApps",
  AppSubscription: "atlasApps",
  AppVersion: "atlasApps",
  AppUpdate: "atlasApps",
  AppDeveloper: "atlasApps",
  AppReview: "atlasApps",
  AppRating: "atlasApps",
  AppLicense: "atlasApps",
  AppWebhook: "atlasApps",
  AppSettings: "atlasApps",
  AppApiKey: "atlasApps",
  AppAuditLog: "atlasApps",
  AppEarnings: "atlasApps",

  // ATLAS Finance — Financial Operating System
  FinanceWorkspace: "atlasFinance",
  FinanceChartOfAccounts: "atlasFinance",
  FinanceAccount: "atlasFinance",
  FinanceJournal: "atlasFinance",
  FinanceJournalEntry: "atlasFinance",
  FinanceLedger: "atlasFinance",
  FinanceTransaction: "atlasFinance",
  FinanceQuotation: "atlasFinance",
  FinancePurchaseOrder: "atlasFinance",
  FinanceExpense: "atlasFinance",
  FinanceIncome: "atlasFinance",
  FinanceTax: "atlasFinance",
  FinanceTaxRate: "atlasFinance",
  FinanceCostCenter: "atlasFinance",
  FinanceBudget: "atlasFinance",
  FinancePeriod: "atlasFinance",
  FinanceCreditNote: "atlasFinance",
  FinanceDebitNote: "atlasFinance",
  FinanceRefund: "atlasFinance",
  FinanceRecurringInvoice: "atlasFinance",
  FinanceRecurringExpense: "atlasFinance",
  FinanceSubscription: "atlasFinance",
  FinanceInstallment: "atlasFinance",
  FinanceReportSnapshot: "atlasFinance",
  FinanceAuditLog: "atlasFinance",

  // ATLAS Mobile — Mobile Business Platform
  MobileDevice: "atlasMobile",
  MobileSession: "atlasMobile",
  MobilePushToken: "atlasMobile",
  MobilePushDelivery: "atlasMobile",
  MobileOfflineQueueItem: "atlasMobile",
  MobileSyncCursor: "atlasMobile",
  MobileSyncConflict: "atlasMobile",
  MobileDeepLink: "atlasMobile",
  MobileCameraJob: "atlasMobile",
  MobileLocationPing: "atlasMobile",
  MobileDashboardWidget: "atlasMobile",
  MobileEntitlement: "atlasMobile",
  MobileRemoteCommand: "atlasMobile",
  MobileAnalyticsEvent: "atlasMobile",
  MobileAuditLog: "atlasMobile",

  // ATLAS Core — integration spine
  CoreOutboxMessage: "atlasCore",
  CoreTimelineEvent: "atlasCore",
  CoreSearchDocument: "atlasCore",
  CoreAnalyticsFact: "atlasCore",
  CoreWorkflowRun: "atlasCore",
  CoreNotificationDispatch: "atlasCore",
  OutboxMessage: "atlasCore",

  Category: "catalog",
  Brand: "catalog",
  InventoryItem: "catalog",

  Listing: "marketplace",
  MarketplaceListing: "marketplace",
  MarketplaceStorefront: "marketplace",
  MarketplaceOffer: "marketplace",
  MarketplaceFlashSale: "marketplace",
  MarketplaceCampaign: "marketplace",
  MarketplaceCollection: "marketplace",
  MarketplaceCheckout: "marketplace",
  MarketplaceShipment: "marketplace",
  MarketplaceFavorite: "marketplace",
  MarketplaceRecommendation: "marketplace",
  MarketplaceAdvertisement: "marketplace",
  MarketplaceTag: "marketplace",
  MarketplaceMonetizationLedger: "marketplace",
  Cart: "marketplace",
  Wishlist: "marketplace",
  Storefront: "marketplace",

  Order: "orders",
  Fulfillment: "orders",

  Payment: "payments",
  Invoice: "payments",
  Escrow: "payments",
  Settlement: "payments",

  Wallet: "wallet",
  LedgerEntry: "wallet",
  Withdrawal: "wallet",

  TokenAccount: "nxrToken",
  TokenTransfer: "nxrToken",
  PresalePosition: "nxrToken",
  NxrToken: "nxrToken",
  NxrWallet: "nxrToken",
  NxrBalance: "nxrToken",
  NxrTransaction: "nxrToken",
  NxrReward: "nxrToken",
  NxrRewardRule: "nxrToken",
  NxrRewardCampaign: "nxrToken",
  NxrLoyaltyAccount: "nxrToken",
  NxrBusinessCredits: "nxrToken",
  NxrTokenPayment: "nxrToken",
  NxrTokenLedger: "nxrToken",
  NxrExchangeRate: "nxrToken",
  NxrTreasury: "nxrToken",
  NxrReserve: "nxrToken",
  NxrBurnEvent: "nxrToken",
  NxrMintEvent: "nxrToken",
  NxrPremiumActivation: "nxrToken",
  NxrStakingPool: "nxrToken",
  NxrGovernanceProposal: "nxrToken",

  Partnership: "partners",
  Document: "documents",

  AssistantThread: "ai",
  Notification: "notifications",
  Review: "reviews",
  MediaAsset: "media",
  ApiKey: "api",
  WebhookEndpoint: "api",
  AuditLog: "audit",
  DomainEvent: "events",
  JobPosting: "jobs",
  Application: "jobs",
  MetricSnapshot: "analytics",

  // NEXAR HQ — sole internal administration
  HqBootstrap: "atlasHq",
  HqPlatformOwner: "atlasHq",
  HqTeamMember: "atlasHq",
  HqCustomRole: "atlasHq",
  HqWebsitePage: "atlasHq",
  HqWebsiteSection: "atlasHq",
  HqWebsiteGlobals: "atlasHq",
  HqAnnouncement: "atlasHq",
  HqMediaAsset: "atlasHq",
  HqEmailTemplate: "atlasHq",
  AdminAction: "atlasHq",
  ModerationCase: "atlasHq",
  PlatformBan: "atlasHq",
};

export function ownerOf(aggregate: string): BoundedContextId | undefined {
  return AGGREGATE_OWNER[aggregate];
}
